alias: 'Switch on the lamp 1 & 2 on motion (1b)'
trigger:
  platform: state
  entity_id: binary_sensor.motion
  from: 'off'
  to: 'on'
condition:
  condition: and
  conditions:
   - condition: state
     entity_id: group.all_devices
     state: 'home'
   - condition: state
     entity_id: 'sun.sun'
     state: 'below_horizon'
action:
  - service: light.turn_on
    entity_id:
     - light.lamp_1
     - light.lamp_2
  - delay:
      minutes: 3
  - service: light.turn_off
    entity_id: 
     - light.lamp_1
     - light.lamp_2
